In [1]:
import pandas as pd

In [4]:
df=pd.read_csv(r'C:\Users\HP\Downloads\NIT_DATA_SCIENCE\GitHub\AI-Phishing_detection\phishshield-ai\dataset\raw\phishing_uci.csv')
df

                                                     url      Type
0      https://docs.google.com/presentation/d/e/2PACX...  Phishing
1        https://btttelecommunniccatiion.weeblysite.com/  Phishing
2                            https://kq0hgp.webwave.dev/  Phishing
3      https://brittishtele1bt-69836.getresponsesite....  Phishing
4             https://bt-internet-105056.weeblysite.com/  Phishing
...                                                  ...       ...
54802   http://www.ezblox.site/free/jennifer111/helpdesk  Phishing
54803  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  Phishing
54804  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  Phishing
54805       http://www.habbocreditosparati.blogspot.com/  Phishing
54806  http://creditiperhabbogratissicuro100.blogspot...  Phishing

[54807 rows x 2 columns]

In [5]:
df.info

<bound method DataFrame.info of                                                      url      Type
0      https://docs.google.com/presentation/d/e/2PACX...  Phishing
1        https://btttelecommunniccatiion.weeblysite.com/  Phishing
2                            https://kq0hgp.webwave.dev/  Phishing
3      https://brittishtele1bt-69836.getresponsesite....  Phishing
4             https://bt-internet-105056.weeblysite.com/  Phishing
...                                                  ...       ...
54802   http://www.ezblox.site/free/jennifer111/helpdesk  Phishing
54803  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  Phishing
54804  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  Phishing
54805       http://www.habbocreditosparati.blogspot.com/  Phishing
54806  http://creditiperhabbogratissicuro100.blogspot...  Phishing

[54807 rows x 2 columns]>

In [11]:
df.isna().all()

url     False
Type    False
dtype: bool

In [12]:
df.isnull()

         url   Type
0      False  False
1      False  False
2      False  False
3      False  False
4      False  False
...      ...    ...
54802  False  False
54803  False  False
54804  False  False
54805  False  False
54806  False  False

[54807 rows x 2 columns]

In [13]:
df.isna().any()

url     False
Type    False
dtype: bool

In [14]:
df.describe()

                                                      url      Type
count                                               54807     54807
unique                                              54805         1
top     https://storage.cloud.google.com/1lordman1man3...  Phishing
freq                                                    3     54807

In [15]:
df1=pd.read_csv(r"C:\Users\HP\Downloads\NIT_DATA_SCIENCE\GitHub\AI-Phishing_detection\phishshield-ai\dataset\raw\phishing.csv")
df1

,Index,UsingIP,LongURL,ShortURL,Symbol@,Redirecting//,PrefixSuffix-,SubDomains,HTTPS,DomainRegLen,...,UsingPopupWindow,IframeRedirection,AgeofDomain,DNSRecording,WebsiteTraffic,PageRank,GoogleIndex,LinksPointingToPage,StatsReport,class
0,0,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
1,1,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
2,2,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
3,3,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1
4,4,-1,0,-1,1,-1,-1,1,1,-1,...,1,1,1,1,1,-1,1,-1,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11049,11049,1,-1,1,-1,1,1,1,1,-1,...,-1,-1,1,1,-1,-1,1,1,1,1
11050,11050,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,1,1,1,1,1,1,-1,1,-1
11051,11051,1,-1,1,1,1,-1,1,-1,-1,...,1,1,1,1,1,-1,1,0,1,-1
11052,11052,-1,-1,1,1,1,-1,-1,-1,1,...,-1,1,1,1,1,-1,1,1,1,-1
11053,11053,-1,-1,1,1,1,-1,-1,-1,1,...,1,1,-1,1,-1,-1,-1,1,-1,-1

In [16]:
df1.info

<bound method DataFrame.info of        Index  UsingIP  LongURL  ShortURL  Symbol@  Redirecting//  \
0          0        1        1         1        1              1
1          1        1        0         1        1              1
2          2        1        0         1        1              1
3          3        1        0        -1        1              1
4          4       -1        0        -1        1             -1
...      ...      ...      ...       ...      ...            ...
11049  11049        1       -1         1       -1              1
11050  11050       -1        1         1       -1             -1
11051  11051        1       -1         1        1              1
11052  11052       -1       -1         1        1              1
11053  11053       -1       -1         1        1              1

       PrefixSuffix-  SubDomains  HTTPS  DomainRegLen  ...  UsingPopupWindow  \
0                 -1           0      1            -1  ...                 1
1                 -1          -1     -1            -1  ...                 1
2                 -1          -1     -1             1  ...                 1
3                 -1           1      1            -1  ...                -1
4                 -1           1      1            -1  ...                 1
...              ...         ...    ...           ...  ...               ...
11049              1           1      1            -1  ...                -1
11050             -1           1     -1            -1  ...                -1
11051             -1           1     -1            -1  ...                 1
11052             -1          -1     -1             1  ...                -1
11053             -1          -1     -1             1  ...                 1

       IframeRedirection  AgeofDomain  DNSRecording  WebsiteTraffic  PageRank  \
0                      1           -1            -1               0        -1
1                      1            1            -1               1        -1
2                      1           -1            -1               1        -1
3                      1           -1            -1               0        -1
4                      1            1             1               1        -1
...                  ...          ...           ...             ...       ...
11049                 -1            1             1              -1        -1
11050                  1            1             1               1         1
11051                  1            1             1               1        -1
11052                  1            1             1               1        -1
11053                  1           -1             1              -1        -1

       GoogleIndex  LinksPointingToPage  StatsReport  class
0                1                    1            1     -1
1                1                    0           -1     -1
2                1                   -1            1     -1
3                1                    1            1      1
4                1                   -1           -1      1
...            ...                  ...          ...    ...
11049            1                    1            1      1
11050            1                   -1            1     -1
11051            1                    0            1     -1
11052            1                    1            1     -1
11053           -1                    1           -1     -1

[11054 rows x 32 columns]>

In [17]:
df1.describe

<bound method NDFrame.describe of        Index  UsingIP  LongURL  ShortURL  Symbol@  Redirecting//  \
0          0        1        1         1        1              1
1          1        1        0         1        1              1
2          2        1        0         1        1              1
3          3        1        0        -1        1              1
4          4       -1        0        -1        1             -1
...      ...      ...      ...       ...      ...            ...
11049  11049        1       -1         1       -1              1
11050  11050       -1        1         1       -1             -1
11051  11051        1       -1         1        1              1
11052  11052       -1       -1         1        1              1
11053  11053       -1       -1         1        1              1

       PrefixSuffix-  SubDomains  HTTPS  DomainRegLen  ...  UsingPopupWindow  \
0                 -1           0      1            -1  ...                 1
1                 -1          -1     -1            -1  ...                 1
2                 -1          -1     -1             1  ...                 1
3                 -1           1      1            -1  ...                -1
4                 -1           1      1            -1  ...                 1
...              ...         ...    ...           ...  ...               ...
11049              1           1      1            -1  ...                -1
11050             -1           1     -1            -1  ...                -1
11051             -1           1     -1            -1  ...                 1
11052             -1          -1     -1             1  ...                -1
11053             -1          -1     -1             1  ...                 1

       IframeRedirection  AgeofDomain  DNSRecording  WebsiteTraffic  PageRank  \
0                      1           -1            -1               0        -1
1                      1            1            -1               1        -1
2                      1           -1            -1               1        -1
3                      1           -1            -1               0        -1
4                      1            1             1               1        -1
...                  ...          ...           ...             ...       ...
11049                 -1            1             1              -1        -1
11050                  1            1             1               1         1
11051                  1            1             1               1        -1
11052                  1            1             1               1        -1
11053                  1           -1             1              -1        -1

       GoogleIndex  LinksPointingToPage  StatsReport  class
0                1                    1            1     -1
1                1                    0           -1     -1
2                1                   -1            1     -1
3                1                    1            1      1
4                1                   -1           -1      1
...            ...                  ...          ...    ...
11049            1                    1            1      1
11050            1                   -1            1     -1
11051            1                    0            1     -1
11052            1                    1            1     -1
11053           -1                    1           -1     -1

[11054 rows x 32 columns]>

In [ ]:
df.isnull(